In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
df = pd.read_csv('Task1-data\deliveries.csv')

In [46]:
df.head()

match_id   season  start_date                             venue  innings  \
0         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
1         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
2         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
3         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
4         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   

   ball batting_team bowling_team      striker  non_striker  ... extras  \
0   0.1      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
1   0.2      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
2   0.3      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
3   0.4      England  New Zealand     DJ Malan  JM Bairstow  ...      0   
4   0.5      England  New Zealand  JM Bairstow     DJ Malan  ...      0   

   wides  noballs  byes  legbyes  penalty  wicket_type  player_dismissed  \
0    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
1    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
2    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
3    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
4    NaN      NaN   NaN      NaN      NaN          NaN               NaN   

  other_wicket_type other_player_dismissed  
0               NaN                    NaN  
1               NaN                    NaN  
2               NaN                    NaN  
3               NaN                    NaN  
4               NaN                    NaN  

[5 rows x 22 columns]

In [47]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [48]:
df['runs_off_bat'].unique()

array([0, 6, 1, 4, 2, 3, 5], dtype=int64)

In [49]:
df['wicket_type'].unique()

array([nan, 'caught', 'bowled', 'caught and bowled', 'lbw', 'run out',
       'stumped', 'retired hurt'], dtype=object)

In [50]:
df['bowling_team'].unique()

array(['New Zealand', 'England', 'Netherlands', 'Pakistan', 'Bangladesh',
       'Afghanistan', 'Sri Lanka', 'South Africa', 'India', 'Australia'],
      dtype=object)

In [51]:
df['other_player_dismissed'].unique()

array([nan])

In [52]:
df['runs_off_bat'].value_counts()

0    9181
1    5525
4    1480
2     726
6     418
3      48
5       2
Name: runs_off_bat, dtype: int64

In [82]:
df2 = df[['match_id','innings','venue','batting_team','bowling_team','runs_off_bat']]


In [83]:
df2.head()

match_id  innings                             venue batting_team  \
0         1        1  Narendra Modi Stadium, Ahmedabad      England   
1         1        1  Narendra Modi Stadium, Ahmedabad      England   
2         1        1  Narendra Modi Stadium, Ahmedabad      England   
3         1        1  Narendra Modi Stadium, Ahmedabad      England   
4         1        1  Narendra Modi Stadium, Ahmedabad      England   

  bowling_team  runs_off_bat  
0  New Zealand             0  
1  New Zealand             6  
2  New Zealand             1  
3  New Zealand             1  
4  New Zealand             4

In [84]:
df2.shape

(17380, 6)

In [85]:
df2.isnull().sum()

match_id        0
innings         0
venue           0
batting_team    0
bowling_team    0
runs_off_bat    0
dtype: int64

In [88]:
filtered_df = df2[df2['runs_off_bat'].isin([4, 6])]


In [89]:
filtered_df.shape

(1898, 6)

In [90]:
filtered_df['Total_Boundaries'] = filtered_df.groupby(['match_id'])['runs_off_bat'].transform('sum')


C:\Users\NISHIT\AppData\Local\Temp\ipykernel_3188\2405892558.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Total_Boundaries'] = filtered_df.groupby(['match_id'])['runs_off_bat'].transform('sum')


In [91]:
filtered_df.head()

match_id  innings                             venue batting_team  \
1          1        1  Narendra Modi Stadium, Ahmedabad      England   
4          1        1  Narendra Modi Stadium, Ahmedabad      England   
20         1        1  Narendra Modi Stadium, Ahmedabad      England   
24         1        1  Narendra Modi Stadium, Ahmedabad      England   
34         1        1  Narendra Modi Stadium, Ahmedabad      England   

   bowling_team  runs_off_bat  Total_Boundaries  
1   New Zealand             6               288  
4   New Zealand             4               288  
20  New Zealand             4               288  
24  New Zealand             4               288  
34  New Zealand             4               288

In [92]:
filtered_df.shape

(1898, 7)

In [93]:
filtered_df_unique = filtered_df.drop_duplicates(subset=['match_id'])


In [94]:
filtered_df_unique.shape

(32, 7)

In [95]:
filtered_df_unique

match_id  innings                                              venue  \
1             1        1                   Narendra Modi Stadium, Ahmedabad   
530           2        1  Rajiv Gandhi International Stadium, Uppal, Hyd...   
1092          3        1  Himachal Pradesh Cricket Association Stadium, ...   
1528          4        1                        Arun Jaitley Stadium, Delhi   
2123          5        1           MA Chidambaram Stadium, Chepauk, Chennai   
2692          6        1  Rajiv Gandhi International Stadium, Uppal, Hyd...   
3264          7        1  Himachal Pradesh Cricket Association Stadium, ...   
3860          8        1  Rajiv Gandhi International Stadium, Uppal, Hyd...   
4479          9        1                        Arun Jaitley Stadium, Delhi   
4998         11        1           MA Chidambaram Stadium, Chepauk, Chennai   
5574         12        1                   Narendra Modi Stadium, Ahmedabad   
6026         13        1                        Arun Jaitley Stadium, Delhi   
6572         14        1  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   
7062         15        1  Himachal Pradesh Cricket Association Stadium, ...   
7603         16        1           MA Chidambaram Stadium, Chepauk, Chennai   
8116         17        1      Maharashtra Cricket Association Stadium, Pune   
8672         18        1                   M Chinnaswamy Stadium, Bengaluru   
9281         19        1  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   
9881         20        1                           Wankhede Stadium, Mumbai   
10336        21        1  Himachal Pradesh Cricket Association Stadium, ...   
10933        22        1           MA Chidambaram Stadium, Chepauk, Chennai   
11563        10        1  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   
12105        23        1                           Wankhede Stadium, Mumbai   
12705        24        1                        Arun Jaitley Stadium, Delhi   
13158        25        1                   M Chinnaswamy Stadium, Bengaluru   
13521        26        1           MA Chidambaram Stadium, Chepauk, Chennai   
14101        27        1  Himachal Pradesh Cricket Association Stadium, ...   
14733        28        1                              Eden Gardens, Kolkata   
15291        29        1  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...   
15831        30        1      Maharashtra Cricket Association Stadium, Pune   
16394        31        1                              Eden Gardens, Kolkata   
16875        32        1      Maharashtra Cricket Association Stadium, Pune   

       batting_team  bowling_team  runs_off_bat  Total_Boundaries  
1           England   New Zealand             6               288  
530        Pakistan   Netherlands             4               254  
1092    Afghanistan    Bangladesh             4               130  
1528   South Africa     Sri Lanka             4               482  
2123      Australia         India             4               150  
2692    New Zealand   Netherlands             4               274  
3264        England    Bangladesh             4               292  
3860      Sri Lanka      Pakistan             4               338  
4479    Afghanistan         India             4               302  
4998     Bangladesh   New Zealand             4               244  
5574       Pakistan         India             4               224  
6026    Afghanistan       England             6               242  
6572      Sri Lanka     Australia             4               216  
7062    Netherlands  South Africa             4               238  
7603    New Zealand   Afghanistan             4               198  
8116     Bangladesh         India             4               266  
8672      Australia      Pakistan             6               402  
9281    Netherlands     Sri Lanka             4               184  
9881   South Africa       England             4               356  
10336   New Zealand         India      