In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv('Task1-data\deliveries.csv')

In [42]:
df.head()

match_id   season  start_date                             venue  innings  \
0         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
1         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
2         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
3         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   
4         1  2023/24  2023-10-05  Narendra Modi Stadium, Ahmedabad        1   

   ball batting_team bowling_team      striker  non_striker  ... extras  \
0   0.1      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
1   0.2      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
2   0.3      England  New Zealand  JM Bairstow     DJ Malan  ...      0   
3   0.4      England  New Zealand     DJ Malan  JM Bairstow  ...      0   
4   0.5      England  New Zealand  JM Bairstow     DJ Malan  ...      0   

   wides  noballs  byes  legbyes  penalty  wicket_type  player_dismissed  \
0    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
1    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
2    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
3    NaN      NaN   NaN      NaN      NaN          NaN               NaN   
4    NaN      NaN   NaN      NaN      NaN          NaN               NaN   

  other_wicket_type other_player_dismissed  
0               NaN                    NaN  
1               NaN                    NaN  
2               NaN                    NaN  
3               NaN                    NaN  
4               NaN                    NaN  

[5 rows x 22 columns]

In [43]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [44]:
df['runs_off_bat'].unique()

array([0, 6, 1, 4, 2, 3, 5], dtype=int64)

In [45]:
df['wicket_type'].unique()

array([nan, 'caught', 'bowled', 'caught and bowled', 'lbw', 'run out',
       'stumped', 'retired hurt'], dtype=object)

In [46]:
df['bowling_team'].unique()

array(['New Zealand', 'England', 'Netherlands', 'Pakistan', 'Bangladesh',
       'Afghanistan', 'Sri Lanka', 'South Africa', 'India', 'Australia'],
      dtype=object)

In [47]:
df['other_player_dismissed'].unique()

array([nan])

In [48]:
df['runs_off_bat'].value_counts()

0    9181
1    5525
4    1480
2     726
6     418
3      48
5       2
Name: runs_off_bat, dtype: int64

## I'm solving the second problem of our Task-1:

## The problem statement is "Total No. of boundaries in World Cup Final Match"

In [49]:
df2 = df[['match_id','innings','venue','batting_team','bowling_team','runs_off_bat']]


In [50]:
df2.head()

match_id  innings                             venue batting_team  \
0         1        1  Narendra Modi Stadium, Ahmedabad      England   
1         1        1  Narendra Modi Stadium, Ahmedabad      England   
2         1        1  Narendra Modi Stadium, Ahmedabad      England   
3         1        1  Narendra Modi Stadium, Ahmedabad      England   
4         1        1  Narendra Modi Stadium, Ahmedabad      England   

  bowling_team  runs_off_bat  
0  New Zealand             0  
1  New Zealand             6  
2  New Zealand             1  
3  New Zealand             1  
4  New Zealand             4

In [51]:
df2.shape

(17380, 6)

In [52]:
df2.isnull().sum()

match_id        0
innings         0
venue           0
batting_team    0
bowling_team    0
runs_off_bat    0
dtype: int64

### I'm filtering out rows which contains only boundaries, i.e. 4 and 6 on a particular ball.

In [53]:
filtered_df = df2[df2['runs_off_bat'].isin([4, 6])]

In [54]:
filtered_df.shape

(1898, 6)

### Counting the total number of boundaries by grouping match_id and innings, and the result is stored in new column name 'Total_Boundaries'.

In [55]:
filtered_df['Total_Boundaries'] = filtered_df.groupby(['match_id','innings'])['runs_off_bat'].transform('count')


C:\Users\NISHIT\AppData\Local\Temp\ipykernel_4476\3508572072.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Total_Boundaries'] = filtered_df.groupby(['match_id','innings'])['runs_off_bat'].transform('count')


In [56]:
filtered_df.head()

match_id  innings                             venue batting_team  \
1          1        1  Narendra Modi Stadium, Ahmedabad      England   
4          1        1  Narendra Modi Stadium, Ahmedabad      England   
20         1        1  Narendra Modi Stadium, Ahmedabad      England   
24         1        1  Narendra Modi Stadium, Ahmedabad      England   
34         1        1  Narendra Modi Stadium, Ahmedabad      England   

   bowling_team  runs_off_bat  Total_Boundaries  
1   New Zealand             6                27  
4   New Zealand             4                27  
20  New Zealand             4                27  
24  New Zealand             4                27  
34  New Zealand             4                27

In [57]:
filtered_df.shape

(1898, 7)

### Removing all the duplicate rows so that I can get total boundaries per match per innings uniquely.

In [58]:
filtered_df_unique = filtered_df.drop_duplicates(subset=['match_id','innings'])


In [59]:
filtered_df_unique.shape

(64, 7)

In [60]:
filtered_df_unique

match_id  innings                                              venue  \
1             1        1                   Narendra Modi Stadium, Ahmedabad   
304           1        2                   Narendra Modi Stadium, Ahmedabad   
530           2        1  Rajiv Gandhi International Stadium, Uppal, Hyd...   
836           2        2  Rajiv Gandhi International Stadium, Uppal, Hyd...   
1092          3        1  Himachal Pradesh Cricket Association Stadium, ...   
...         ...      ...                                                ...   
16120        30        2      Maharashtra Cricket Association Stadium, Pune   
16394        31        1                              Eden Gardens, Kolkata   
16663        31        2                              Eden Gardens, Kolkata   
16875        32        1      Maharashtra Cricket Association Stadium, Pune   
17166        32        2      Maharashtra Cricket Association Stadium, Pune   

       batting_team  bowling_team  runs_off_bat  Total_Boundaries  
1           England   New Zealand             6                27  
304     New Zealand       England             4                38  
530        Pakistan   Netherlands             4                36  
836     Netherlands      Pakistan             4                24  
1092    Afghanistan    Bangladesh             4                17  
...             ...           ...           ...               ...  
16120   Afghanistan     Sri Lanka             4                24  
16394    Bangladesh      Pakistan             4                22  
16663      Pakistan    Bangladesh             4                28  
16875  South Africa   New Zealand             4                41  
17166   New Zealand  South Africa             4                21  

[64 rows x 7 columns]

In [61]:
filtered_df_unique.shape

(64, 7)

In [62]:
filtered_df_unique = filtered_df_unique.drop(columns=['match_id','innings'])


In [63]:
filtered_df_unique = filtered_df_unique.drop(columns=['runs_off_bat'])

### Applying Label-Encoder on  venue , batting_team , bowling_team  columns

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
lst = ['venue','batting_team','bowling_team']
for i in lst:
    filtered_df_unique[i] = le.fit_transform(filtered_df_unique[i])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(le_name_mapping)

{'Arun Jaitley Stadium, Delhi': 0, 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow': 1, 'Eden Gardens, Kolkata': 2, 'Himachal Pradesh Cricket Association Stadium, Dharamsala': 3, 'M Chinnaswamy Stadium, Bengaluru': 4, 'MA Chidambaram Stadium, Chepauk, Chennai': 5, 'Maharashtra Cricket Association Stadium, Pune': 6, 'Narendra Modi Stadium, Ahmedabad': 7, 'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 8, 'Wankhede Stadium, Mumbai': 9}
{'Afghanistan': 0, 'Australia': 1, 'Bangladesh': 2, 'England': 3, 'India': 4, 'Netherlands': 5, 'New Zealand': 6, 'Pakistan': 7, 'South Africa': 8, 'Sri Lanka': 9}
{'Afghanistan': 0, 'Australia': 1, 'Bangladesh': 2, 'England': 3, 'India': 4, 'Netherlands': 5, 'New Zealand': 6, 'Pakistan': 7, 'South Africa': 8, 'Sri Lanka': 9}


In [65]:
filtered_df_unique.head()

venue  batting_team  bowling_team  Total_Boundaries
1         7             3             6                27
304       7             6             3                38
530       8             7             5                36
836       8             5             7                24
1092      3             0             2                17

In [66]:
X = filtered_df_unique.drop(columns='Total_Boundaries')
y = filtered_df_unique['Total_Boundaries']

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

### Applying the XGBoost regressor on my data to predict the boundaries of final match

In [68]:
import xgboost as xgb
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error,r2_score


param_grid = {
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'n_estimators': [100, 200, 300]
}

xg_reg = xgb.XGBRegressor(objective='reg:squarederror')

grid_search = GridSearchCV(estimator=xg_reg, param_grid=param_grid, scoring='neg_mean_squared_error', cv=5)

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
print(f'Best Hyperparameters: {best_params}')

best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Root Mean Squared Error on Test Set:", np.sqrt(mse))

Best Hyperparameters: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
Root Mean Squared Error on Test Set: 11.805805502896684


## We are assuming the final is between India and South Africa in Narendra Modi Stadium, Ahmedabad(pre-decided).

In [69]:
# 4 represents India
# 8 represents South Africa
# 7 in venue represents Narendra Modi Stadium, Ahmedabad
new_data1 = pd.DataFrame({'venue': [7], 'batting_team': [4], 'bowling_team': [8]})
new_data2 = pd.DataFrame({'venue': [7], 'batting_team': [8], 'bowling_team': [4]})

y_pred1 = best_model.predict(new_data1)
print("Boundaries when India bats:", y_pred1)
y_pred2 = best_model.predict(new_data2)
print("Boundaries when South Africa bats:",y_pred2)
print("Total Boundaries in whole match:", y_pred1+y_pred2)

Boundaries when India bats: [28.48503]
Boundaries when South Africa bats: [30.156712]
Total Boundaries in whole match: [58.64174]


## According to our model, the Boundaries when India bats against South Africa is around 29(4's and 6's Together) and when South Africa bats against India is around 30(4's and 6's Together). So overall the boundaries will be approximately 59 (4's and 6's Together) in whole match.